#!/bin/sh

lightning run app \
  --cloud \
  --open-ui=false \
  --env ECHO_MODEL_SIZE=base \
  --env ECHO_ENABLE_MULTI_TENANCY=true \
  --env ECHO_RECOGNIZER_CLOUD_COMPUTE=gpu \
  --env ECHO_RECOGNIZER_MIN_REPLICAS=1 \
  --env ECHO_RECOGNIZER_MAX_IDLE_SECONDS_PER_WORK=600 \
  --env ECHO_RECOGNIZER_MAX_PENDING_CALLS_PER_WORK=100 \
  --env ECHO_RECOGNIZER_AUTOSCALER_CRON_SCHEDULE="*/5 * * * *" \
  --env ECHO_YOUTUBER_CLOUD_COMPUTE=cpu-small \
  --env ECHO_YOUTUBER_MIN_REPLICAS=1 \
  --env ECHO_YOUTUBER_MAX_IDLE_SECONDS_PER_WORK=600 \
  --env ECHO_YOUTUBER_MAX_PENDING_CALLS_PER_WORK=100 \
  --env ECHO_YOUTUBER_AUTOSCALER_CRON_SCHEDULE="*/5 * * * *" \
  --env ECHO_GARBAGE_COLLECTION_CRON_SCHEDULE="*/30 * * * *" \
  --env ECHO_GARBAGE_COLLECTION_MAX_AGE_SECONDS=86400 \
  --env ECHO_USER_ECHOES_LIMIT=100 \
  --env ECHO_SOURCE_TYPE_FILE_ENABLED=true \
  --env ECHO_SOURCE_TYPE_RECORDING_ENABLED=true \
  --env ECHO_SOURCE_TYPE_YOUTUBE_ENABLED=true \
  --env ECHO_VIDEO_SOURCE_MAX_DURATION_SECONDS=900 \
  --env REACT_APP_ECHO_RECORDING_SOURCE_MAX_DURATION_SECONDS=60 \
  --env ECHO_DATABASE_CLOUD_COMPUTE=cpu \
  --env ECHO_LOADBALANCER_AUTH_TOKEN=abc123 \
  --env ECHO_ANALYTICS_ENABLED=false \
  app.py
